---
# tasks file for cis-ubuntu-20.04

- name: Validate OS is Ubuntu and Version is 20.04, fail if not.
  fail:
      msg: "This role is only applicable against Ubuntu 20.04. You are running it on OS: {{ ansible_distribution }} and version: {{ ansible_distribution_major_version }}, which does not comply."
  when:
      - not ansible_distribution == "Ubuntu"
      - not ansible_distribution_version == "20.04"
  # tags:
  #     - always
