---
# tasks file for CIS Ubuntu Linux 20.04 LTS Benchmark v1.0.0 Section 2 BENCHMARKS

- name: "2.1.1 | Ensure xinetd is not installed (Automated)"
  apt:
    name: "{{ ubuntu_2004_cis_section1_rule_2_1_1_params_package_name }}"
    state: "{{ ubuntu_2004_cis_section1_rule_2_1_1_params_package_state }}"
    purge: "{{ ubuntu_2004_cis_section1_rule_2_1_1_params_package_purge }}"
  when:
    - ubuntu_2004_cis_section1_rule_2_1_1
    - ubuntu_2004_cis_section2
  tags:
    - section2
    - rule_2_1_1
    - level_1

- name: "2.1.2 | Ensure openbsd-inetd is not installed (Automated)"
  apt:
    name: "{{ ubuntu_2004_cis_section1_rule_2_1_2_params_package_name }}"
    state: "{{ ubuntu_2004_cis_section1_rule_2_1_2_params_package_state }}"
    purge: "{{ ubuntu_2004_cis_section1_rule_2_1_2_params_package_purge }}"
  when:
    - ubuntu_2004_cis_section1_rule_2_1_2
    - ubuntu_2004_cis_section2
  tags:
    - section2
    - rule_2_1_2
    - level_1
