---
# tasks file for CIS Ubuntu Linux 20.04 LTS Benchmark v1.0.0 Section 2 BENCHMARKS

- name: "3.1.1 | Disable IPv6 (Manual)"
  replace:
    path: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_path }}"
    regexp: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_regex }}"
    replace: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_replace }}"
    owner: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_owner }}"
    group: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_group }}"
    mode: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_mode }}"
  notify:
    - update grub configuration
    - reapply permissions to bootloader configuration
    # ^ to handle the fact that handlers run after tasks which change bootloader config permissions
  when:
    - not ubuntu_2004_cis_require_ipv6
    - ubuntu_2004_cis_section3_rule_3_1_1
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_1_1
    - level_2

- name: "3.1.2 | Ensure wireless interfaces are disabled (Automated)"
  shell: "{{ ubuntu_2004_cis_section3_rule_3_1_2_params_shell }}"
  args:
    executable: "{{ ubuntu_2004_cis_section3_rule_3_1_2_params_executable }}"
  when:
    - not ubuntu_2004_cis_require_wireless
    - ubuntu_2004_cis_section3_rule_3_1_2
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_1_2
    - level_1
    - level_2

- name: "3.2.1 | Ensure packet redirect sending is disabled (Automated)"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_state }}"
    reload: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_reload }}"
    sysctl_set: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_sysctl_set }}"
  with_items:
    - { name: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_all_send_redirects }}", value: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_all_send_redirects_value }}" }
    - { name: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_default_send_redirects }}", value: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_default_send_redirects_value }}" }
  notify:
    - flush ipv4 route
  when:
    - not ubuntu_2004_cis_require_router
    - ubuntu_2004_cis_section3_rule_3_2_1
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_2_1
    - level_1

- name: "3.2.2 | Ensure IP forwarding is disabled (Automated)"
  block:

    - name: "3.2.2 | Ensure IP forwarding is disabled (Automated) | IPv4 forwarding"
      sysctl:
        name: "{{ ubuntu_2004_cis_section3_rule_3_2_2_params_ipv4_forwarding }}"
        value: "{{ ubuntu_2004_cis_section3_rule_3_2_2_params_ipv4_forwarding_value }}"
        state: "{{ ubuntu_2004_cis_section3_rule_3_2_2_params_state }}"
        reload: "{{ ubuntu_2004_cis_section3_rule_3_2_2_params_reload }}"
        sysctl_set: "{{ ubuntu_2004_cis_section3_rule_3_2_2_params_sysctl_set }}"
      notify:
        - flush ipv4 route

    - name: "3.2.2 | Ensure IP forwarding is disabled (Automated) | IPv6 forwarding"
      sysctl:
        name: "{{ ubuntu_2004_cis_section3_rule_3_2_2_params_ipv6_forwarding }}"
        value: "{{ ubuntu_2004_cis_section3_rule_3_2_2_params_ipv6_forwarding_value }}"
        state: "{{ ubuntu_2004_cis_section3_rule_3_2_2_params_state }}"
        reload: "{{ ubuntu_2004_cis_section3_rule_3_2_2_params_reload }}"
        sysctl_set: "{{ ubuntu_2004_cis_section3_rule_3_2_2_params_sysctl_set }}"
      notify:
        - flush ipv6 route
      when:
        - ubuntu_2004_cis_require_ipv6

  when:
    - not ubuntu_2004_cis_require_router
    - ubuntu_2004_cis_section3_rule_3_2_2
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_2_2
    - level_1

- name: "3.3.1 | Ensure source routed packets are not accepted (Automated)"
  block:

    - name: "3.3.1 | Ensure source routed packets are not accepted (Automated) | IPv4 source routed packets"
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_state }}"
        reload: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_reload }}"
        sysctl_set: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_sysctl_set }}"
      with_items:
        - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_ipv4all_accept_source_route }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_ipv4all_accept_source_route_value }}" }
        - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_ipv4default_accept_source_route }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_ipv4default_accept_source_route_value }}" }
      notify:
        - flush ipv4 route

    - name: "3.3.1 | Ensure source routed packets are not accepted (Automated) | IPv6 source routed packets"
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_state }}"
        reload: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_reload }}"
        sysctl_set: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_sysctl_set }}"
      with_items:
        - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_ipv6all_accept_source_route }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_ipv6all_accept_source_route_value }}" }
        - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_ipv6default_accept_source_route }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_1_params_ipv6default_accept_source_route_value }}" }
      notify:
        - flush ipv6 route
      when:
        - ubuntu_2004_cis_require_ipv6

  when:
    - ubuntu_2004_cis_section3_rule_3_3_1
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_3_1
    - level_1

- name: "3.3.2 | Ensure ICMP redirects are not accepted (Automated)"
  block:

    - name: "3.3.2 | Ensure ICMP redirects are not accepted (Automated) | IPv4 ICMP redirects rejected"
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_state }}"
        reload: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_reload }}"
        sysctl_set: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_sysctl_set }}"
      with_items:
        - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_ipv4all_accept_redirects }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_ipv4all_accept_redirects_value }}" }
        - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_ipv4default_accept_redirects }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_ipv4default_accept_redirects_value }}" }
      notify:
        - flush ipv4 route

    - name: "3.3.2 | Ensure ICMP redirects are not accepted (Automated) | IPv6 ICMP redirects rejected"
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_state }}"
        reload: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_reload }}"
        sysctl_set: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_sysctl_set }}"
      with_items:
        - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_ipv6all_accept_redirects }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_ipv6all_accept_redirects_value }}" }
        - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_ipv6default_accept_redirects }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_2_params_ipv6default_accept_redirects_value }}" }
      notify:
        - flush ipv6 route
      when:
        - ubuntu_2004_cis_require_ipv6

  when:
    - ubuntu_2004_cis_section3_rule_3_3_2
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_3_2
    - level_1

- name: "3.3.3 | Ensure secure ICMP redirects are not accepted (Automated)"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ ubuntu_2004_cis_section3_rule_3_3_3_params_state }}"
    reload: "{{ ubuntu_2004_cis_section3_rule_3_3_3_params_reload }}"
    sysctl_set: "{{ ubuntu_2004_cis_section3_rule_3_3_3_params_sysctl_set }}"
  with_items:
    - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_3_params_ipv4all_secure_redirects }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_3_params_ipv4all_secure_redirects_value }}" }
    - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_3_params_ipv4default_secure_redirects }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_3_params_ipv4default_secure_redirects_value }}" }
  notify:
    - flush ipv4 route
  when:
    - ubuntu_2004_cis_section3_rule_3_3_3
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_3_3
    - level_1

- name: "3.3.4 | Ensure suspicious packets are logged (Automated)"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ ubuntu_2004_cis_section3_rule_3_3_4_params_state }}"
    reload: "{{ ubuntu_2004_cis_section3_rule_3_3_4_params_reload }}"
    sysctl_set: "{{ ubuntu_2004_cis_section3_rule_3_3_4_params_sysctl_set }}"
  with_items:
    - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_4_params_ipv4all_log_martians }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_4_params_ipv4all_log_martians_value }}" }
    - { name: "{{ ubuntu_2004_cis_section3_rule_3_3_4_params_ipv4default_log_martians }}", value: "{{ ubuntu_2004_cis_section3_rule_3_3_4_params_ipv4default_log_martians_value }}" }
  notify:
    - flush ipv4 route
  when:
    - ubuntu_2004_cis_section3_rule_3_3_4
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_3_4
    - level_1
