---
# tasks file for CIS Ubuntu Linux 20.04 LTS Benchmark v1.0.0 Section 5 BENCHMARKS

- name: "5.1.1 | Ensure cron daemon is enabled and running (Automated)"
  systemd:
    name: "{{ ubuntu_2004_cis_section5_rule_5_1_1_params_cron_service_name }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_1_1_params_cron_service_state }}"
    enabled: "{{ ubuntu_2004_cis_section5_rule_5_1_1_params_cron_service_enabled }}"
  when:
    - ubuntu_2004_cis_section5_rule_5_1_1
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_1
    - level_1

- name: "5.1.2 | Ensure permissions on /etc/crontab are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section5_rule_5_1_2_params_path }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_1_2_params_state }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_1_2_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_1_2_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_1_2_params_mode }}"
  when:
    - ubuntu_2004_cis_section5_rule_5_1_2
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_2
    - level_1

- name: "5.1.3 | Ensure permissions on /etc/cron.hourly are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_path }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_state }}"
    recurse: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_recurse }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_mode }}"
  when:
    - ubuntu_2004_cis_section5_rule_5_1_3
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_3
    - level_1
