---
# tasks file for CIS Ubuntu Linux 20.04 LTS Benchmark v1.0.0 Section 4 BENCHMARKS

- name: "4.1.1.1 | Ensure auditd is installed (Automated)"
  apt:
    name: "{{ ubuntu_2004_cis_section4_rule_4_1_1_1_params_name }}"
    state: "{{ ubuntu_2004_cis_section4_rule_4_1_1_1_params_state }}"
  when:
    - ubuntu_2004_cis_section4_rule_4_1_1_1
    - ubuntu_2004_cis_section4
  tags:
    - section4
    - rule_4_1_1_1
    - level_2

- name: "4.1.1.2 | Ensure auditd service is enabled (Automated)"
  systemd:
    name: "{{ ubuntu_2004_cis_section4_rule_4_1_1_2_params_auditd_service_name }}"
    enabled: "{{ ubuntu_2004_cis_section4_rule_4_1_1_2_params_auditd_service_enabled }}"
  when:
    - ubuntu_2004_cis_section4_rule_4_1_1_2
    - ubuntu_2004_cis_section4
  tags:
    - section4
    - rule_4_1_1_2
    - level_2

- name: "4.1.1.3 | Ensure auditing for processes that start prior to auditd is enabled (Automated)"
  replace:
    path: "{{ ubuntu_2004_cis_section4_rule_4_1_1_3_params_auditd_enabled_path }}"
    regexp: "{{ ubuntu_2004_cis_section4_rule_4_1_1_3_params_auditd_enabled_regex }}"
    replace: "{{ ubuntu_2004_cis_section4_rule_4_1_1_3_params_auditd_enabled_replace }}"
    owner: "{{ ubuntu_2004_cis_section4_rule_4_1_1_3_params_auditd_enabled_owner }}"
    group: "{{ ubuntu_2004_cis_section4_rule_4_1_1_3_params_auditd_enabled_group }}"
    mode: "{{ ubuntu_2004_cis_section4_rule_4_1_1_3_params_auditd_enabled_mode }}"
  notify:
    - update grub configuration
    - reapply permissions to bootloader configuration
    # ^ to handle the fact that handlers run after tasks which change bootloader config permissions
  when:
    - ubuntu_2004_cis_section4_rule_4_1_1_3
    - ubuntu_2004_cis_section4
  tags:
    - section4
    - rule_4_1_1_3
    - level_2

- name: "4.1.1.4 | Ensure audit_backlog_limit is sufficient (Automated)"
  replace:
    path: "{{ ubuntu_2004_cis_section4_rule_4_1_1_4_params_auditd_backlog_path }}"
    regexp: "{{ ubuntu_2004_cis_section4_rule_4_1_1_4_params_auditd_backlog_regex }}"
    replace: "{{ ubuntu_2004_cis_section4_rule_4_1_1_4_params_auditd_backlog_replace }}"
    owner: "{{ ubuntu_2004_cis_section4_rule_4_1_1_4_params_auditd_backlog_owner }}"
    group: "{{ ubuntu_2004_cis_section4_rule_4_1_1_4_params_auditd_backlog_group }}"
    mode: "{{ ubuntu_2004_cis_section4_rule_4_1_1_4_params_auditd_backlog_mode }}"
  notify:
    - update grub configuration
    - reapply permissions to bootloader configuration
    # ^ to handle the fact that handlers run after tasks which change bootloader config permissions
  when:
    - ubuntu_2004_cis_section4_rule_4_1_1_4
    - ubuntu_2004_cis_section4
  tags:
    - section4
    - rule_4_1_1_4
    - level_2

- name: "4.1.2.1 | Ensure audit log storage size is configured (Automated)"
  lineinfile:
    path: "{{ ubuntu_2004_cis_section4_rule_4_1_2_1_params_path }}"
    line: "{{ ubuntu_2004_cis_section4_rule_4_1_2_1_params_line }}"
    regexp: "{{ ubuntu_2004_cis_section4_rule_4_1_2_1_params_regexp }}"
    state: "{{ ubuntu_2004_cis_section4_rule_4_1_2_1_params_state }}"
    owner: "{{ ubuntu_2004_cis_section4_rule_4_1_2_1_params_owner }}"
    group: "{{ ubuntu_2004_cis_section4_rule_4_1_2_1_params_group }}"
    mode: "{{ ubuntu_2004_cis_section4_rule_4_1_2_1_params_mode }}"
  notify:
    - auditd restart
  when:
    - ubuntu_2004_cis_section4_rule_4_1_2_1
    - ubuntu_2004_cis_section4
  tags:
    - section4
    - rule_4_1_2_1
    - level_2
