---
# tasks file for CIS UBUNTU 20.04 SECTION 1 BENCHMARKS

- name: "1.1.1.1 | Ensure mounting of cramfs filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_1
  tags:
    - section1
    - rule_1_1_1_1

- name: "1.1.1.1 | Remove cramfs kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_1
  tags:
    - section1
    - rule_1_1_1_1

- name: "1.1.1.2 | Ensure mounting of freevxfs filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_2
  tags:
    - section1
    - rule_1_1_1_2

- name: "1.1.1.2 | Remove freevxfs kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_2
  tags:
    - section1
    - rule_1_1_1_2

- name: "1.1.1.3 | Ensure mounting of jffs2 filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_3
  tags:
    - section1
    - rule_1_1_1_3

- name: "1.1.1.3 | Remove jffs2 kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_3
  tags:
    - section1
    - rule_1_1_1_3

- name: "1.1.1.4 | Ensure mounting of hfs filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_4
  tags:
    - section1
    - rule_1_1_1_4

- name: "1.1.1.4 | Remove hfs kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_4
  tags:
    - section1
    - rule_1_1_1_4

- name: "1.1.1.5 | Ensure mounting of hfsplus filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_5
  tags:
    - section1
    - rule_1_1_1_5

- name: "1.1.1.5 | Remove hfsplus kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_5
  tags:
    - section1
    - rule_1_1_1_5
