---
# tasks file for CIS UBUNTU 20.04 SECTION 1 BENCHMARKS

- name: "1.1.1.1 | Ensure mounting of cramfs filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_1
  tags:
    - section1
    - rule_1_1_1_1
    - level_1

- name: "1.1.1.1 | Remove cramfs kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_1_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_1
  tags:
    - section1
    - rule_1_1_1_1
    - level_1

- name: "1.1.1.2 | Ensure mounting of freevxfs filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_2
  tags:
    - section1
    - rule_1_1_1_2
    - level_1

- name: "1.1.1.2 | Remove freevxfs kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_2_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_2
  tags:
    - section1
    - rule_1_1_1_2
    - level_1

- name: "1.1.1.3 | Ensure mounting of jffs2 filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_3
  tags:
    - section1
    - rule_1_1_1_3
    - level_1

- name: "1.1.1.3 | Remove jffs2 kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_3_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_3
  tags:
    - section1
    - rule_1_1_1_3
    - level_1

- name: "1.1.1.4 | Ensure mounting of hfs filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_4
  tags:
    - section1
    - rule_1_1_1_4
    - level_1

- name: "1.1.1.4 | Remove hfs kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_4_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_4
  tags:
    - section1
    - rule_1_1_1_4
    - level_1

- name: "1.1.1.5 | Ensure mounting of hfsplus filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_5
  tags:
    - section1
    - rule_1_1_1_5
    - level_1

- name: "1.1.1.5 | Remove hfsplus kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_5_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_5
  tags:
    - section1
    - rule_1_1_1_5
    - level_1

- name: "1.1.1.6 | Ensure mounting of udf filesystems is disabled (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_6_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_6_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_6_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_6_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_6_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_6
  tags:
    - section1
    - rule_1_1_1_6
    - level_1

- name: "1.1.1.6 | Remove udf kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_6_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_6_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_6
  tags:
    - section1
    - rule_1_1_1_6
    - level_1

- name: "1.1.1.7 | Ensure mounting of FAT filesystems is limited (Automated)"
  template:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_1_7_params['source']  }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_1_7_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_1_7_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_1_7_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_1_7_params['mode'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_7
  tags:
    - section1
    - rule_1_1_1_7
    - level_1

- name: "1.1.1.7 | Remove FAT (vfat) kernel module (Automated)"
  modprobe:
    name: "{{ ubuntu_2004_cis_section1_rule_1_1_1_7_params['module_name'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_1_7_params['module_state'] }}"
  when: ubuntu_2004_cis_section1_rule_1_1_1_7
  tags:
    - section1
    - rule_1_1_1_7
    - level_1

- name: "1.1.2 | Ensure /tmp is configured (Automated)"
  copy:
    src: "{{ ubuntu_2004_cis_section1_rule_1_1_2_params['src'] }}"
    dest: "{{ ubuntu_2004_cis_section1_rule_1_1_2_params['dest'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_2_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_2_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_2_params['mode'] }}"
    backup: "{{ ubuntu_2004_cis_section1_rule_1_1_2_params['backup'] }}"
    remote_src: "{{ ubuntu_2004_cis_section1_rule_1_1_2_params['remote_src'] }}"
    force: "{{ ubuntu_2004_cis_section1_rule_1_1_2_params['force'] }}"
  notify:
    - systemd tmp.mount reload
  when: ubuntu_2004_cis_section1_rule_1_1_2
  tags:
    - section1
    - rule_1_1_2
    - level_1

- name: "1.1.3 | Ensure nodev option set on /tmp partition (Automated)\n
         1.1.4 | Ensure nosuid option set on /tmp partition (Automated)\n
         1.1.5 | Ensure noexec option set on /tmp partition (Automated)"
  ini_file:
    path: "{{ ubuntu_2004_cis_section1_rule_1_1_3_and_1_1_4_and_1_1_5_params['path'] }}"
    section: "{{ ubuntu_2004_cis_section1_rule_1_1_3_and_1_1_4_and_1_1_5_params['section'] }}"
    option: "{{ ubuntu_2004_cis_section1_rule_1_1_3_and_1_1_4_and_1_1_5_params['option'] }}"
    value: "{{ ubuntu_2004_cis_section1_rule_1_1_3_and_1_1_4_and_1_1_5_params['value'] }}"
    owner: "{{ ubuntu_2004_cis_section1_rule_1_1_3_and_1_1_4_and_1_1_5_params['owner'] }}"
    group: "{{ ubuntu_2004_cis_section1_rule_1_1_3_and_1_1_4_and_1_1_5_params['group'] }}"
    mode: "{{ ubuntu_2004_cis_section1_rule_1_1_3_and_1_1_4_and_1_1_5_params['mode'] }}"
    state: "{{ ubuntu_2004_cis_section1_rule_1_1_3_and_1_1_4_and_1_1_5_params['state'] }}"
    backup: "{{ ubuntu_2004_cis_section1_rule_1_1_3_and_1_1_4_and_1_1_5_params['backup'] }}"
    no_extra_spaces: "{{ ubuntu_2004_cis_section1_rule_1_1_3_and_1_1_4_and_1_1_5_params['no_extra_spaces'] }}"
  notify:
    - systemd tmp.mount reload
  when:
    - ubuntu_2004_cis_section1_rule_1_1_3
    - ubuntu_2004_cis_section1_rule_1_1_4
    - ubuntu_2004_cis_section1_rule_1_1_5
  tags:
    - section1
    - rule_1_1_3
    - rule_1_1_4
    - rule_1_1_5
    - level_1

  - name: "1.1.7 | Ensure nodev option set on /dev/shm partition (Automated)\n
           1.1.8 | Ensure nosuid option set on /dev/shm partition (Automated)\n
           1.1.9 | Ensure noexec option set on /dev/shm partition (Automated)"
    mount:
      src: "{{ ubuntu_2004_cis_section1_rule_1_1_7_and_1_1_8_and_1_1_9_params['src'] }}"
      path: "{{ ubuntu_2004_cis_section1_rule_1_1_7_and_1_1_8_and_1_1_9_params['path'] }}"
      fstype: "{{ ubuntu_2004_cis_section1_rule_1_1_7_and_1_1_8_and_1_1_9_params['fstype'] }}"
      opts: "{{ ubuntu_2004_cis_section1_rule_1_1_7_and_1_1_8_and_1_1_9_params['opts'] }}"
      dump: "{{ ubuntu_2004_cis_section1_rule_1_1_7_and_1_1_8_and_1_1_9_params['dump'] }}"
      passno: "{{ ubuntu_2004_cis_section1_rule_1_1_7_and_1_1_8_and_1_1_9_params['passno'] }}"
      state: "{{ ubuntu_2004_cis_section1_rule_1_1_7_and_1_1_8_and_1_1_9_params['state'] }}"
      backup: "{{ ubuntu_2004_cis_section1_rule_1_1_7_and_1_1_8_and_1_1_9_params['backup'] }}"
    when:
      - ubuntu_2004_cis_section1_rule_1_1_7
      - ubuntu_2004_cis_section1_rule_1_1_8
      - ubuntu_2004_cis_section1_rule_1_1_9
    tags:
      - section1
      - rule_1_1_7
      - rule_1_1_8
      - rule_1_1_9
      - level_1
