---
# tasks file for CIS Ubuntu Linux 20.04 LTS Benchmark v1.0.0 Section 5 BENCHMARKS

- name: "5.1.1 | Ensure cron daemon is enabled and running (Automated)"
  systemd:
    name: "{{ ubuntu_2004_cis_section5_rule_5_1_1_params_cron_service_name }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_1_1_params_cron_service_state }}"
    enabled: "{{ ubuntu_2004_cis_section5_rule_5_1_1_params_cron_service_enabled }}"
  when:
    - ubuntu_2004_cis_section5_rule_5_1_1
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_1
    - level_1

- name: "5.1.2 | Ensure permissions on /etc/crontab are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section5_rule_5_1_2_params_path }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_1_2_params_state }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_1_2_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_1_2_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_1_2_params_mode }}"
  when:
    - ubuntu_2004_cis_section5_rule_5_1_2
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_2
    - level_1

- name: "5.1.3 | Ensure permissions on /etc/cron.hourly are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_path }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_state }}"
    recurse: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_recurse }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_1_3_params_mode }}"
  when:
    - ubuntu_2004_cis_section5_rule_5_1_3
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_3
    - level_1

- name: "5.1.4 | Ensure permissions on /etc/cron.daily are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section5_rule_5_1_4_params_path }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_1_4_params_state }}"
    recurse: "{{ ubuntu_2004_cis_section5_rule_5_1_4_params_recurse }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_1_4_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_1_4_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_1_4_params_mode }}"
  when:
    - ubuntu_2004_cis_section5_rule_5_1_4
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_4
    - level_1

- name: "5.1.5 | Ensure permissions on /etc/cron.weekly are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section5_rule_5_1_5_params_path }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_1_5_params_state }}"
    recurse: "{{ ubuntu_2004_cis_section5_rule_5_1_5_params_recurse }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_1_5_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_1_5_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_1_5_params_mode }}"
  when:
    - ubuntu_2004_cis_section5_rule_5_1_5
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_5
    - level_1

- name: "5.1.6 | Ensure permissions on /etc/cron.monthly are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section5_rule_5_1_6_params_path }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_1_6_params_state }}"
    recurse: "{{ ubuntu_2004_cis_section5_rule_5_1_6_params_recurse }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_1_6_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_1_6_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_1_6_params_mode }}"
  when:
    - ubuntu_2004_cis_section5_rule_5_1_6
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_6
    - level_1

- name: "5.1.7 | Ensure permissions on /etc/cron.d are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section5_rule_5_1_7_params_path }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_1_7_params_state }}"
    recurse: "{{ ubuntu_2004_cis_section5_rule_5_1_7_params_recurse }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_1_7_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_1_7_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_1_7_params_mode }}"
  when:
    - ubuntu_2004_cis_section5_rule_5_1_7
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_7
    - level_1

- name: "5.1.8 | Ensure cron is restricted to authorized users (Automated)"
  block:

    - name: "5.1.8 | Ensure cron is restricted to authorized users (Automated) | Remove cron.deny"
      file:
        path: "{{ ubuntu_2004_cis_section5_rule_5_1_8_params_cron_deny_path }}"
        state: "{{ ubuntu_2004_cis_section5_rule_5_1_8_params_cron_deny_state }}"
        mode: "{{ ubuntu_2004_cis_section5_rule_5_1_8_params_cron_deny_mode }}"

    - name: "5.1.8 | Ensure cron is restricted to authorized users (Automated) | Set cron.allow"
      template:
        src: "{{ ubuntu_2004_cis_section5_rule_5_1_8_params_cron_allow_source }}"
        dest: "{{ ubuntu_2004_cis_section5_rule_5_1_8_params_cron_allow_dest }}"
        owner: "{{ ubuntu_2004_cis_section5_rule_5_1_8_params_cron_allows_owner }}"
        group: "{{ ubuntu_2004_cis_section5_rule_5_1_8_params_cron_allow_group }}"
        mode: "{{ ubuntu_2004_cis_section5_rule_5_1_8_params_cron_allow_mode }}"

  when:
    - ubuntu_2004_cis_section5_rule_5_1_8
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_8
    - level_1

- name: "5.1.9 | Ensure at is restricted to authorized users (Automated)"
  block:

    - name: "5.1.9 | Ensure at is restricted to authorized users (Automated) | Remove at.deny"
      file:
        path: "{{ ubuntu_2004_cis_section5_rule_5_1_9_params_at_deny_path }}"
        state: "{{ ubuntu_2004_cis_section5_rule_5_1_9_params_at_deny_state }}"
        mode: "{{ ubuntu_2004_cis_section5_rule_5_1_9_params_at_deny_mode }}"

    - name: "5.1.9 | Ensure at is restricted to authorized users (Automated) | Set at.allow"
      template:
        src: "{{ ubuntu_2004_cis_section5_rule_5_1_9_params_at_allow_source }}"
        dest: "{{ ubuntu_2004_cis_section5_rule_5_1_9_params_at_allow_dest }}"
        owner: "{{ ubuntu_2004_cis_section5_rule_5_1_9_params_at_allows_owner }}"
        group: "{{ ubuntu_2004_cis_section5_rule_5_1_9_params_at_allow_group }}"
        mode: "{{ ubuntu_2004_cis_section5_rule_5_1_9_params_at_allow_mode }}"

  when:
    - ubuntu_2004_cis_section5_rule_5_1_9
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_1_9
    - level_1

- name: "5.2.1 | Ensure permissions on /etc/ssh/sshd_config are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section5_rule_5_2_1_params_path }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_2_1_params_state }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_2_1_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_2_1_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_2_1_params_mode }}"
  notify:
    - sshd restart
  when:
    - ubuntu_2004_cis_require_ssh_server
    - ubuntu_2004_cis_section5_rule_5_2_1
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_2_1
    - level_1

- name: "5.2.2 | Ensure permissions on SSH private host key files are configured (Automated)"
  block:

    - name: "5.2.2 | Ensure permissions on SSH private host key files are configured (Automated) | Set ownership for SSH private host keys"
      command: "{{ ubuntu_2004_cis_section5_rule_5_2_2_params_onwership_command }}"
      notify:
        - sshd restart

    - name: "5.2.2 | Ensure permissions on SSH private host key files are configured (Automated) | Set permissions for SSH private host keys"
      command: "{{ ubuntu_2004_cis_section5_rule_5_2_2_params_permissions_command }}"
      notify:
        - sshd restart

  when:
    - ubuntu_2004_cis_require_ssh_server
    - ubuntu_2004_cis_section5_rule_5_2_2
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_2_2
    - level_1

- name: "5.2.3 | Ensure permissions on SSH public host key files are configured (Automated)"
  block:

    - name: "5.2.3 | Ensure permissions on SSH public host key files are configured (Automated) | Set ownership for SSH private host keys"
      command: "{{ ubuntu_2004_cis_section5_rule_5_2_3_params_onwership_command }}"
      notify:
        - sshd restart

    - name: "5.2.3 | Ensure permissions on SSH public host key files are configured (Automated) | Set permissions for SSH private host keys"
      command: "{{ ubuntu_2004_cis_section5_rule_5_2_3_params_permissions_command }}"
      notify:
        - sshd restart

  when:
    - ubuntu_2004_cis_require_ssh_server
    - ubuntu_2004_cis_section5_rule_5_2_3
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_2_3
    - level_1

- name: "5.2.4 | Ensure SSH LogLevel is appropriate (Automated)"
  lineinfile:
    path: "{{ ubuntu_2004_cis_section5_rule_5_2_4_params_path }}"
    line: "{{ ubuntu_2004_cis_section5_rule_5_2_4_params_line }}"
    regexp: "{{ ubuntu_2004_cis_section5_rule_5_2_4_params_regexp }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_2_4_params_state }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_2_4_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_2_4_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_2_4_params_mode }}"
  notify:
    - sshd restart
  when:
    - ubuntu_2004_cis_require_ssh_server
    - ubuntu_2004_cis_section5_rule_5_2_4
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_2_4
    - level_1

- name: "5.2.5 | Ensure SSH X11 forwarding is disabled (Automated)"
  lineinfile:
    path: "{{ ubuntu_2004_cis_section5_rule_5_2_5_params_path }}"
    line: "{{ ubuntu_2004_cis_section5_rule_5_2_5_params_line }}"
    regexp: "{{ ubuntu_2004_cis_section5_rule_5_2_5_params_regexp }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_2_5_params_state }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_2_5_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_2_5_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_2_5_params_mode }}"
  notify:
    - sshd restart
  when:
    - ubuntu_2004_cis_require_ssh_server
    - ubuntu_2004_cis_section5_rule_5_2_5
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_2_5
    - level_1
    - level_2

- name: "5.2.6 | Ensure SSH MaxAuthTries is set to 4 or less (Automated)"
  lineinfile:
    path: "{{ ubuntu_2004_cis_section5_rule_5_2_6_params_path }}"
    line: "{{ ubuntu_2004_cis_section5_rule_5_2_6_params_line }}"
    regexp: "{{ ubuntu_2004_cis_section5_rule_5_2_6_params_regexp }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_2_6_params_state }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_2_6_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_2_6_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_2_6_params_mode }}"
  notify:
    - sshd restart
  when:
    - ubuntu_2004_cis_require_ssh_server
    - ubuntu_2004_cis_section5_rule_5_2_6
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_2_6
    - level_1

- name: "5.2.7 | Ensure SSH IgnoreRhosts is enabled (Automated)"
  lineinfile:
    path: "{{ ubuntu_2004_cis_section5_rule_5_2_7_params_path }}"
    line: "{{ ubuntu_2004_cis_section5_rule_5_2_7_params_line }}"
    regexp: "{{ ubuntu_2004_cis_section5_rule_5_2_7_params_regexp }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_2_7_params_state }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_2_7_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_2_7_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_2_7_params_mode }}"
  notify:
    - sshd restart
  when:
    - ubuntu_2004_cis_require_ssh_server
    - ubuntu_2004_cis_section5_rule_5_2_7
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_2_7
    - level_1

- name: "5.2.8 | Ensure SSH HostbasedAuthentication is disabled (Automated)"
  lineinfile:
    path: "{{ ubuntu_2004_cis_section5_rule_5_2_8_params_path }}"
    line: "{{ ubuntu_2004_cis_section5_rule_5_2_8_params_line }}"
    regexp: "{{ ubuntu_2004_cis_section5_rule_5_2_8_params_regexp }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_2_8_params_state }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_2_8_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_2_8_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_2_8_params_mode }}"
  notify:
    - sshd restart
  when:
    - ubuntu_2004_cis_require_ssh_server
    - ubuntu_2004_cis_section5_rule_5_2_8
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_2_8
    - level_1

- name: "5.2.9 | Ensure SSH root login is disabled (Automated)"
  lineinfile:
    path: "{{ ubuntu_2004_cis_section5_rule_5_2_9_params_path }}"
    line: "{{ ubuntu_2004_cis_section5_rule_5_2_9_params_line }}"
    regexp: "{{ ubuntu_2004_cis_section5_rule_5_2_9_params_regexp }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_2_9_params_state }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_2_9_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_2_9_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_2_9_params_mode }}"
  notify:
    - sshd restart
  when:
    - ubuntu_2004_cis_require_ssh_server
    - ubuntu_2004_cis_section5_rule_5_2_9
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_2_9
    - level_1

- name: "5.2.10 | Ensure SSH PermitEmptyPasswords is disabled (Automated)"
  lineinfile:
    path: "{{ ubuntu_2004_cis_section5_rule_5_2_10_params_path }}"
    line: "{{ ubuntu_2004_cis_section5_rule_5_2_10_params_line }}"
    regexp: "{{ ubuntu_2004_cis_section5_rule_5_2_10_params_regexp }}"
    state: "{{ ubuntu_2004_cis_section5_rule_5_2_10_params_state }}"
    owner: "{{ ubuntu_2004_cis_section5_rule_5_2_10_params_owner }}"
    group: "{{ ubuntu_2004_cis_section5_rule_5_2_10_params_group }}"
    mode: "{{ ubuntu_2004_cis_section5_rule_5_2_10_params_mode }}"
  notify:
    - sshd restart
  when:
    - ubuntu_2004_cis_require_ssh_server
    - ubuntu_2004_cis_section5_rule_5_2_10
    - ubuntu_2004_cis_section5
  tags:
    - section5
    - rule_5_2_10
    - level_1
