---
# tasks file for CIS Ubuntu Linux 20.04 LTS Benchmark v1.0.0 Section 2 BENCHMARKS

- name: "2.1.1 | Ensure xinetd is not installed (Automated)"
  apt:
    name: "{{ ubuntu_2004_cis_section2_rule_2_1_1_params_package_name }}"
    state: "{{ ubuntu_2004_cis_section2_rule_2_1_1_params_package_state }}"
    purge: "{{ ubuntu_2004_cis_section2_rule_2_1_1_params_package_purge }}"
  when:
    - ubuntu_2004_cis_section2_rule_2_1_1
    - ubuntu_2004_cis_section2
  tags:
    - section2
    - rule_2_1_1
    - level_1

- name: "2.1.2 | Ensure openbsd-inetd is not installed (Automated)"
  apt:
    name: "{{ ubuntu_2004_cis_section2_rule_2_1_2_params_package_name }}"
    state: "{{ ubuntu_2004_cis_section2_rule_2_1_2_params_package_state }}"
    purge: "{{ ubuntu_2004_cis_section2_rule_2_1_2_params_package_purge }}"
  when:
    - ubuntu_2004_cis_section2_rule_2_1_2
    - ubuntu_2004_cis_section2
  tags:
    - section2
    - rule_2_1_2
    - level_1

- name: "2.2.1.1 | Ensure time synchronization is in use (Automated)"
  block:

    - name: "2.2.1.1 | Ensure time synchronization is in use (Automated) | Enable systemd-timesyncd if time synchronization is systemd-timesyncd"
      systemd:
        name: "{{ ubuntu_2004_cis_section2_rule_2_2_1_1_params_timesyncd_service_name }}"
        enabled: "{{ ubuntu_2004_cis_section2_rule_2_2_1_1_params_timesyncd_service_enabled_true }}"
      when:
        - ubuntu_2004_cis_time_synchronization == "systemd-timesyncd"

    - name: "2.2.1.1 | Ensure time synchronization is in use (Automated) | Mask systemd-timesyncd if time synchronization is not systemd-timesyncd"
      systemd:
        name: "{{ ubuntu_2004_cis_section2_rule_2_2_1_1_params_timesyncd_service_name }}"
        masked: "{{ ubuntu_2004_cis_section2_rule_2_2_1_1_params_timesyncd_service_masked_true }}"
      when:
        - ubuntu_2004_cis_time_synchronization != "systemd-timesyncd"

    - name: "2.2.1.1 | Ensure time synchronization is in use (Automated) | Installing NTP or Chrony if time synchronization is not systemd-timesyncd"
      apt:
        name: "{{ ubuntu_2004_cis_time_synchronization }}"
        state: "{{ ubuntu_2004_cis_time_synchronization_package_state }}"
      when:
        - ubuntu_2004_cis_time_synchronization != "systemd-timesyncd"


    - name: "2.2.1.1 | Ensure time synchronization is in use (Automated) | Purge Chrony if time synchronization is NTP or systemd-timesyncd"
      apt:
        name: "{{ ubuntu_2004_cis_section2_rule_2_2_1_1_params_chrony_package }}"
        state: "{{ ubuntu_2004_cis_section2_rule_2_2_1_1_params_chrony_package_state }}"
        purge: "{{ ubuntu_2004_cis_section2_rule_2_2_1_1_params_chrony_package_purge }}"
      when:
        - ubuntu_2004_cis_time_synchronization != "chrony"

    - name: "2.2.1.1 | Ensure time synchronization is in use (Automated) | Purge NTP if time synchronization is Chrony or systemd-timesyncd"
      apt:
        name: "{{ ubuntu_2004_cis_section2_rule_2_2_1_1_params_ntp_package }}"
        state: "{{ ubuntu_2004_cis_section2_rule_2_2_1_1_params_ntp_package_state }}"
        purge: "{{ ubuntu_2004_cis_section2_rule_2_2_1_1_params_ntp_package_purge }}"
      when:
        - ubuntu_2004_cis_time_synchronization != "ntp"

  when:
    - ubuntu_2004_cis_section2_rule_2_2_1_1
    - ubuntu_2004_cis_section2
  tags:
    - section2
    - rule_2_2_1_1
    - level_1
