---
# tasks file for CIS Ubuntu Linux 20.04 LTS Benchmark v1.0.0 Section 6 BENCHMARKS

- name: "6.1.1 | Audit system file permissions (Manual)"
  block:

    - name: "6.1.1 | Audit system file permissions (Manual) | Propagate Template"
      template:
        src: "{{ ubuntu_2004_cis_section6_rule_6_1_1_params_template_source }}"
        dest: "{{ ubuntu_2004_cis_section6_rule_6_1_1_params_template_dest }}"
        owner: "{{ ubuntu_2004_cis_section6_rule_6_1_1_params_template_owner }}"
        group: "{{ ubuntu_2004_cis_section6_rule_6_1_1_params_template_group }}"
        mode: "{{ ubuntu_2004_cis_section6_rule_6_1_1_params_template_mode }}"

    - name: "6.1.1 | Audit system file permissions (Manual) | Set Cron"
      cron:
        name: "{{ ubuntu_2004_cis_section6_rule_6_1_1_params_cron_name }}"
        job: "{{ ubuntu_2004_cis_section6_rule_6_1_1_params_cron_job }}"
        user: "{{ ubuntu_2004_cis_section6_rule_6_1_1_params_cron_user }}"
        special_time: "{{ ubuntu_2004_cis_section6_rule_6_1_1_params_cron_time }}"

  when:
    - ubuntu_2004_cis_section6_rule_6_1_1
    - ubuntu_2004_cis_section6
  tags:
    - section6
    - rule_6_1_1
    - level_2

- name: "6.1.2 | Ensure permissions on /etc/passwd are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section6_rule_6_1_2_params_path }}"
    state: "{{ ubuntu_2004_cis_section6_rule_6_1_2_params_state }}"
    owner: "{{ ubuntu_2004_cis_section6_rule_6_1_2_params_owner }}"
    group: "{{ ubuntu_2004_cis_section6_rule_6_1_2_params_group }}"
    mode: "{{ ubuntu_2004_cis_section6_rule_6_1_2_params_mode }}"
  when:
    - ubuntu_2004_cis_section6_rule_6_1_2
    - ubuntu_2004_cis_section6
  tags:
    - section6
    - rule_6_1_2
    - level_1

- name: "6.1.3 | Ensure permissions on /etc/gshadow- are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section6_rule_6_1_3_params_path }}"
    state: "{{ ubuntu_2004_cis_section6_rule_6_1_3_params_state }}"
    owner: "{{ ubuntu_2004_cis_section6_rule_6_1_3_params_owner }}"
    group: "{{ ubuntu_2004_cis_section6_rule_6_1_3_params_group }}"
    mode: "{{ ubuntu_2004_cis_section6_rule_6_1_3_params_mode }}"
  when:
    - ubuntu_2004_cis_section6_rule_6_1_3
    - ubuntu_2004_cis_section6
  tags:
    - section6
    - rule_6_1_3
    - level_1

- name: "6.1.4 | Ensure permissions on /etc/shadow are configured (Automated)"
  file:
    path: "{{ ubuntu_2004_cis_section6_rule_6_1_4_params_path }}"
    state: "{{ ubuntu_2004_cis_section6_rule_6_1_4_params_state }}"
    owner: "{{ ubuntu_2004_cis_section6_rule_6_1_4_params_owner }}"
    group: "{{ ubuntu_2004_cis_section6_rule_6_1_4_params_group }}"
    mode: "{{ ubuntu_2004_cis_section6_rule_6_1_4_params_mode }}"
  when:
    - ubuntu_2004_cis_section6_rule_6_1_4
    - ubuntu_2004_cis_section6
  tags:
    - section6
    - rule_6_1_4
    - level_1
