---
# tasks file for CIS Ubuntu Linux 20.04 LTS Benchmark v1.0.0 Section 2 BENCHMARKS

- name: "3.1.1 | Disable IPv6 (Manual)"
  replace:
    path: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_path }}"
    regexp: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_regex }}"
    replace: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_replace }}"
    owner: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_owner }}"
    group: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_group }}"
    mode: "{{ ubuntu_2004_cis_section3_rule_3_1_1_params_mode }}"
  notify:
    - update grub configuration
    - reapply permissions to bootloader configuration
    # ^ to handle the fact that handlers run after tasks which change bootloader config permissions
  when:
    - not ubuntu_2004_cis_require_ipv6
    - ubuntu_2004_cis_section3_rule_3_1_1
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_1_1
    - level_2

- name: "3.1.2 | Ensure wireless interfaces are disabled (Automated)"
  shell: "{{ ubuntu_2004_cis_section3_rule_3_1_2_params_shell }}"
  args:
    executable: "{{ ubuntu_2004_cis_section3_rule_3_1_2_params_executable }}"
  when:
    - not ubuntu_2004_cis_require_wireless
    - ubuntu_2004_cis_section3_rule_3_1_2
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_1_2
    - level_1
    - level_2

- name: "3.2.1 | Ensure packet redirect sending is disabled (Automated)"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_state }}"
    reload: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_reload }}"
    sysctl_set: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_sysctl_set }}"
  with_items:
    - { name: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_all_send_redirects }}", value: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_all_send_redirects_value }}" }
    - { name: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_default_send_redirects }}", value: "{{ ubuntu_2004_cis_section3_rule_3_2_1_params_default_send_redirects_value }}" }
  notify:
    - flush ipv4 route
  when:
    - not ubuntu_2004_cis_require_router
    - ubuntu_2004_cis_section3_rule_3_2_1
    - ubuntu_2004_cis_section3
  tags:
    - section3
    - rule_3_2_1
    - level_1
