---
# handlers file for CIS UBUNTU 20.04 BENCHMARKS

- name: systemd tmp.mount reload
  become: true
  systemd:
    name: tmp.mount
    daemon_reload: yes
    enabled: yes
    masked: no
    state: reloaded

- name: update grub configuration
  become: true
  command: update-grub

- name: reapply permissions to bootloader configuration
  become: true
  file:
    path: /boot/grub/grub.cfg
    mode: '0400'
    owner: root
    group: root
    state: file

- name: reload gdm
  become: true
  command: dpkg-reconfigure gdm3

- name: chrony restart
  become: true
  systemd:
    name: chrony
    enabled: yes
    state: restarted

- name: ntp restart
  become: true
  systemd:
    name: ntp
    enabled: yes
    state: restarted
