---
- name: Example Playbook to apply cis_ubuntu_2004 role with all the default values.
  hosts: localhost
  connection: local
  become: yes
  gather_facts: true
  roles:
    - cis_ubuntu_2004
  vars:
    ansible_python_interpreter: /usr/bin/python3
